//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Otakims = new HashSet<Otakim>();
        }
    
        public int codeBook { get; set; }
        public string name { get; set; }
        public Nullable<int> codAauthor { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> codeCategory { get; set; }
        public Nullable<int> codeCrowd { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> numOtakim { get; set; }
    
        public virtual Aauthor Aauthor { get; set; }
        public virtual Category Category { get; set; }
        public virtual Crowd Crowd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otakim> Otakims { get; set; }
    }
}
