//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LendingItem
    {
        public int codeLending { get; set; }
        public int codeOtek { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> returnDate { get; set; }
    
        public virtual Lending Lending { get; set; }
        public virtual Otakim Otakim { get; set; }
    }
}
